package_name: express                               #имя пакеда для анализа
repository_url: https://registry.npmjs.org          #URL-адрес репозитория или путь к файлу тестового репозитория
test_repository_mode: false                         #Режим работы с тестовым репозиторием
package_version: latest                             #Версия пакета
output_filename: dependency_graph.txt               #Имя сгенерированного файла с изображением графа
ascii_tree_output: true                             #Режим вывода зависимостей в формате ASCII-дерева
max_depth: 3                                        #Максимальная глубина анализа зависимостей
filter_substring: ""                                #Подстрока для фильтрации пакетов
