package_name: example-package
repository_url: https://github.com/example/repo
test_repository_mode: false
package_version: 1.0.0
output_filename: dependency_graph.png
ascii_tree_output: true
max_depth: 3
filter_substring: test